In [ ]:
#Example 01: code for initializing NumPy array.
import numpy as np
a = np.array([0,1,2])
print(type(a))
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
a[0] = 5
print(a)

b=np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0,0],b[0,1],b[1,0])

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]
(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [4]:
#Example 02: Creating NumPy array
import numpy as np

a = np.zeros((3,3))
print(a)
b = np.ones((2,2))
print(b)
c = np.full((3,3),7)
print(c)
d = np.random.random((3,3))
print(d)
e = np.eye(3)
print(e)
f = np.array([2,3,1,0])
print(f)
g = np.arange(20)
print(g)
h = np.array([[0,1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)
i = np.arange(1,8,dtype=float)
print(i)
j = np.linspace(2,4,5)
print(j)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.1852962  0.69377663 0.19776193]
 [0.64604766 0.41734029 0.62910586]
 [0.91780802 0.24850161 0.69592097]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]
[1. 2. 3. 4. 5. 6. 7.]
[2.  2.5 3.  3.5 4. ]


In [5]:
#Example 3: NumPy data types
import numpy as np 

x = np.array([0, 1])
y = np.array([2.0, 3.0])
z = np.array([5, 6], dtype=np.int64)
print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


In [6]:
#Example 4: Python program to demonstrate indexing in numpy
import numpy as np

arr = np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],[3, -7, 4, 2.0]])
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)
cond = arr > 0 
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [7]:
#Example 5: Python program to demonstrate basic operations on single array
import numpy as np

a = np.array([1, 2, 5, 3])
print ("Adding 1 to every element:", a+1)
print ("Subtracting 3 from each element:", a-3)
print ("Multiplying each element by 10:", a*10)
print ("Squaring each element:", a**2)
a *= 2
print ("Doubled each element of original array:", a)
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)


Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [8]:
#Example 6: Python program to demonstrate unary operators in numpy
import numpy as np

arr = np.array([[1, 5, 6],[4, 7, 2],[3, 1, 9]])
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
print ("Column-wise minimum elements:",arr.min(axis = 0))
print ("Sum of all array elements:",arr.sum())
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [9]:
#Example 7: Python program to demonstrate binary operators in Numpy
import numpy as np

a = np.array([[1, 2],[3, 4]])
b = np.array([[4, 3],[2, 1]])
print ("Array sum:\n", a + b)
print ("Array multiplication:\n", a*b)
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [10]:
#Example 8: Python program to demonstrate universal functions in numpy
import numpy as np

a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [12]:
#Example 9: simple python program to find the inverse of an array (without exception handling)
import numpy as np

arr = np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],[3, -7, 4, 2.0]])
inverse = np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])